### PR TITLE
feat(core): get param name from function arguments

### LINKED ISSUE #6: Infer decorated objects name from class name
In our example API we've written param usage like so
```ts
// I think we should add the ability to infer name from command and cli modules too
@Command({})
export class GenerateCommand implements Executable {
   execute(
      // Here we would infer name from parameter name
      @Param({}) url: string,
      // Or override it
      @Param({ name: 'uri' }) secondUri: string
   ) { }
}
```
Almost everytime the name you'd give for the cli to display will be the same you use in your code. It should be possible for every of our domain object to have their name inferred from the code, or overriden if you actually specify it. 
That is:
- Cli
- Command
- Param
- Option

### PR DESCRIPTION
**Pull request by wbhob**
Fix #6

### CODE REVIEW

**Comment by MonsieurMan** [comment]
@wbhob Are you ok if I make this PR more global, that is add the same behavior for `CLI`, `Command`, `Param`, `Option` as I stated in #6 ?

**Comment by wbhob** [comment]
The behavior already works for Option, and is unnecessary for the rest.

**Comment by wbhob** [comment]
Can we merge?

**Comment by MonsieurMan** [comment]
@wbhob, I'll just add a few things at the end of today and I'll let you review them. :ok_hand:

**Comment by wbhob** [comment]
Ok, the sooner the better. Right now, I'm working on help and need this functionality asap.

**Pull request merged**
